### ISSUE TITLE
Multilayer?

### ISSUE THREAD

**Issue by X3msnake** [Reonarudo/pcb2photon#1]
Greetings. How can i do multilayer from multiple image filed?

**Comment by X3msnake** [comment]
@Reonarudo

**Comment by Reonarudo** [comment]
Currently, each input image will be a different output print file.
How do you see the multilayer functionality working in a PCB exposure context?

**Comment by X3msnake** [comment]
Not in the PCB context.

But we need a alternative to make files for photon from images. 

There is one Master that has know-how in voxel manipulation and has some algorithms that he wants to share with us in order to do model hollowing from image slices.

Also there is a python project based on your findings on reversing the .photon here: https://github.com/NardJ/PhotonFileUtils

If you have interest in lending us some help i'll be glad to ask him to add you to the project team ;)

**Comment by Reonarudo** [comment]
This utility function is directed towards PCBs. To add this functionality I will need some more reasoning behind it. 
But it is doable, I would probably create a new flag like `-m` or `-merge`. I will check back on this once the other functionality is done.

**Comment by X3msnake** [comment]
@Reonarudo I know you can always give us a hand with the Photon utils project

https://github.com/NardJ/PhotonFileUtils

PCB / Silkscreen exposure could be one of the things in the menu.

I'm hoping @Antharon can join us there too and bring his voxel algorithms to the table for 2D hollowing of the files

**Comment by X3msnake** [comment]
This is already implemented 

here: https://github.com/Photonsters/PhotonFileEditor and here: https://github.com/Photonsters/PhotonFileValidator
