### ISSUE TITLE
PhotonFileTemplate.bt error

### ISSUE THREAD

**Issue by Jianxuncui** [Reonarudo/pcb2photon#10]
Hi.

I tried your PhotonFileTemplate.bt in 010editor, but it couldn't run.
There seems an error in this line "    previewImage previewImage; "
Do you have any suggestions to fix that?

Thanks

**Comment by Reonarudo** [comment]
Hi,
Is it possible to share the file where it fails? Can't diagnose the issue without more information.

**Comment by Reonarudo** [comment]
Seems to work. This is how I do it:
![loading template_low](https://user-images.githubusercontent.com/348029/47748778-88dfe080-dc83-11e8-867f-14fb334d726c.gif)

I'm not using the most recent version of 010 I can update it on the weekend and see if any problem arises.

**Comment by Reonarudo** [comment]
I've tested with a newer version and still works as expected. I'll close this issue for now.
